### ISSUE TITLE
get_rgba deviates color output

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#112]
Hi,

Im using this extremely usefull method from `Kirki_Color` class but im getting mixed results.
When I try to create a 65% opacity of the `rgba(0, 135, 204, 1)` color, what I actually get is `rgba(0,8,124, 0.65)` meaning that the color has substantially shifter from the original hue. 

Note that the original color was passed to the function in HEX format `#0087cc`.

Is there anything I can do to avoid/minimize this color mutations?

Thanks.

**Comment by aristath** [comment]
Hey there!

Can you please try replacing `includes/libraries/class-kirki-color.php` with this one: https://gist.github.com/aristath/303026ca0c5565d1108b

Let me know if that fixes your issue!

**Comment by lmartins** [comment]
Hey Aristeides.
Yes, this does solve the issue. Thanks man! 
Should I close this issue or do you want it open before the change is merged to the codebase?

**Comment by aristath** [comment]
Leave it open...

I did some more changes on that gist, can you please try with the new one and let me know if the issue stays resolved with that?

Don't close this, I'll close it once we merge the development branch. :)

**Comment by lmartins** [comment]
@aristath 
Actually there's still a slight shift in color as you can see here:
https://cloudup.com/c50IMcxIhtb

Testing the that latest revision now.

**Comment by lmartins** [comment]
Here's the update, the blue box above is parsing the color with 100% opacity so we can reliably compare hues:
https://cloudup.com/c04VXyOl-rp

The box bellow is just outputting the straight color value in HEX.

The shift is way better now, still not perfect though.

**Comment by aristath** [comment]
I just tested this:

``` php
<?php echo Kirki_Color::get_rgba('#0087cc', 70 ); ?>
```

The result I got was `rgba(0,135,204, 0.7)` which looks 100% correct to me!

**Comment by lmartins** [comment]
Ops, sorry @aristath I was evaluating two slightly different vars.
Yes, it's just perfect :)

**Comment by aristath** [comment]
Awesome! I'm closing this one. :+1:
