### ISSUE TITLE
active_callback not working for checkboxes

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1809]
### Issue description:
Hi @aristath,

active callbacks don't seem to work for checkboxes any more. 

### Version used:
3.0.25

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'theme', array(
	'type' => 'select',
	'settings' => 'my_setting',
	'label' => esc_attr__( 'My Label', 'textdomain' ),
	'section' => 'my_section',
	'default' => 'option1',
	'priority' => 0,
	'multiple' => 1,
	'choices' => array(
		'option1' => esc_attr__( 'Show', 'textdomain' ),
		'option2' => esc_attr__( 'Hide', 'textdomain' ),
	),
) );

Kirki::add_field( 'theme', array(
	'type' => 'checkbox',
	'settings' => 'my_setting2',
	'label' => esc_attr__( 'My Other Label', 'textdomain' ),
	'section' => 'my_section',
	'priority' => 2,
	'active_callback' => array(
		array(
		'setting' => 'my_setting',
		'operator' => '!==',
		'value' => 'option2',
		),
	)
) );
```

**Comment by sergeysedykh** [comment]
Same here.

I was using 3.0.16 in my projects and it was fine.

In the latest version some fields are displayed even if they shouldn't according to the active_callback rules.

Nothing fancy with the config or the fields: trying to display / hide fields based on the switch (=checkbox) field value.

**Comment by two-points** [comment]
Even I am experiencing the same issue. It was working fine earlier.

**Comment by aristath** [comment]
fixed in the dev branch, will be included in v3.0.26 👍

**Comment by sergeysedykh** [comment]
Thanks a lot, @aristath!

**Comment by sergeysedykh** [comment]
I've just checked the dev version and it's working fine again. Thank you!

**Comment by sergeysedykh** [comment]
I'm afraid, I was too quick in my conclusions. The commit fixed the issue partially.

There's still something wrong with the active_callback.

It's not only the matter of checkboxes, but applies to multiple active_callback conditions.

```

Kirki::add_field(
	'custom_theme_mod', array(
		'type'        => 'toggle',
		'settings'    => 'home_archive_default',
		'label'       => esc_html__( 'Default Settings', 'text-domain' ),
		'description' => esc_html__( 'You may change the default settings in Layout &rarr; ', 'text-domain' ) . esc_html__( 'Post Archive', 'text-domain' ),
		'section'     => 'home',
		'default'     => true,
		'priority'    => 10,
	)
);

Kirki::add_field(
	'custom_theme_mod', array(
		'type'        => 'radio-image',
		'settings'    => 'home_archive_type',
		'label'       => esc_html__( 'Type', 'text-domain' ),
		'section'     => 'home',
		'default'     => 'standard',
		'priority'    => 10,
		'choices'     => array(
			'standard'  => $template_directory_uri . '/images/layout-full.png',
			'list'      => $template_directory_uri . '/images/layout-list.png',
			'grid'      => $template_directory_uri . '/images/layout-grid.png',
			'masonry'   => $template_directory_uri . '/images/layout-masonry.png',
		),
		'active_callback' => array(
			array(
				'setting'  => 'home_archive_default',
				'operator' => '==',
				'value'    => false,
			),
		),
	)
);

Kirki::add_field(
	'custom_theme_mod', array(
		'type'        => 'select',
		'settings'    => 'home_columns',
		'label'       => esc_html__( 'Columns', 'text-domain' ),
		'description' => esc_html__( 'Three- and four-column layouts are visible on larger screens only.', 'text-domain' ),
		'section'     => 'home',
		'default'     => '2',
		'priority'    => 10,
		'choices'     => array(
			'2'         => '2',
			'3'         => '3',
			'4'         => '4',
		),
		'active_callback' => array(
			array(
				array(
					'setting'  => 'home_archive_default',
					'operator' => '==',
					'value'    => false,
				),
			),
			array(
				array(
					'setting'  => 'home_archive_type',
					'operator' => '==',
					'value'    => 'grid',
				),
				array(
					'setting'  => 'home_archive_type',
					'operator' => '==',
					'value'    => 'masonry',
				),
			),
		),
	)
);
```

I'm still seeing the Columns select field, even if Default Settings are active:

![image](https://user-images.githubusercontent.com/36392769/37253986-1e7dce28-254a-11e8-9372-57f9b5b9ea4e.png)


And if I disable Default Settings and select the List (second option) type layout, I still see the Columns field, however it should be visible only if Masonry or Grid is selected:

![image](https://user-images.githubusercontent.com/36392769/37254000-3e514356-254a-11e8-9246-3c50269daf1d.png)

I would highly appreciate, if you could check the issue, @aristath. Thanks!

**Comment by aristath** [comment]
Took me 4 hours, but I believe it's ok now.
The problem was that in your code you're using nested requirements and that was not properly implemented (nested arrays change the relation from AND to OR and vice-versa every time you go a level deeper).
It should be ok now no matter how many levels deep you go 👍

**Comment by sergeysedykh** [comment]
Awesome, it's working now! And looks like it's working much faster now.

Many thanks, you're a ⭐️!

I'm a little bit confused about this sentence though:

<blockquote>It should be ok now no matter how many levels deep you go 👍</blockquote>

What do you mean by many levels?

I thought there're only two levels in active_callback. The first level is with AND operator, while the nested levels are with OR operator.

Or has this recently been changed in Kirki?

**Comment by aristath** [comment]
> I thought there're only two levels in active_callback. The first level is with AND operator, while the nested levels are with OR operator.

Actually it's alternating.
So 1st level is AND, 2nd OR, 3rd AND, 4th OR etc.
Usually no more than 2 levels are needed so this is not that well-known.

For example you could do something like this if needed
```php
'active_callback' => array(
	array(
		array(
			'setting'  => 'setting1',
			'operator' => '==',
			'value'    => false,
		),
		// OR
		array(
			array(
				'setting'  => 'setting2',
				'operator' => '==',
				'value'    => true,
			),
			// AND
			array(
				array(
					'setting'  => 'setting3',
					'operator' => '==',
					'value'    => true,
				),
				// OR
				array(
					'setting'  => 'setting4',
					'operator' => '==',
					'value'    => true,
				),
			),
		),
	),
	// AND
	array(
		array(
			'setting'  => 'setting5',
			'operator' => '==',
			'value'    => true,
		),
		// OR
		array(
			'setting'  => 'setting6',
			'operator' => '==',
			'value'    => false,
		),
	),
),
```

**Comment by sergeysedykh** [comment]
Thanks for explanation! Looks much more flexible now, though I can hardly image conditions with more than two levels.

**Comment by Stas0238** [comment]
> > I thought there're only two levels in active_callback. The first level is with AND operator, while the nested levels are with OR operator.
> 
> Actually it's alternating.
> So 1st level is AND, 2nd OR, 3rd AND, 4th OR etc.
> Usually no more than 2 levels are needed so this is not that well-known.
> 
> For example you could do something like this if needed
> 
> ```
> 'active_callback' => array(
> 	array(
> 		array(
> 			'setting'  => 'setting1',
> 			'operator' => '==',
> 			'value'    => false,
> 		),
> 		// OR
> 		array(
> 			array(
> 				'setting'  => 'setting2',
> 				'operator' => '==',
> 				'value'    => true,
> 			),
> 			// AND
> 			array(
> 				array(
> 					'setting'  => 'setting3',
> 					'operator' => '==',
> 					'value'    => true,
> 				),
> 				// OR
> 				array(
> 					'setting'  => 'setting4',
> 					'operator' => '==',
> 					'value'    => true,
> 				),
> 			),
> 		),
> 	),
> 	// AND
> 	array(
> 		array(
> 			'setting'  => 'setting5',
> 			'operator' => '==',
> 			'value'    => true,
> 		),
> 		// OR
> 		array(
> 			'setting'  => 'setting6',
> 			'operator' => '==',
> 			'value'    => false,
> 		),
> 	),
> ),
> ```

@aristath Can you please, add this explanation to your documentation too :)
