### ISSUE TITLE
Multiple (general) issues ...

### ISSUE THREAD

**Issue by Anydog** [themeum/kirki#356]
I just pulled latest version and ... sorry to say, but a lot seems to be not working ...
I'm not seeing some fields in **preview** and some are not working **at all**:
- default values not loaded in preview
- font changes ( I used select2 and `Kirki_Fonts::get_font_choices` with `array( 'element'  => 'body', 'property' => 'font-family',) in "output" )` - although, those are saved and visible on frontend
- \- - ( i know you introduced new typography field, which is GREAT, btw)
- number slider (also, saved successfully on frontend)
- image upload not being previewed AND saved ...
- and still ... switch is not saving at all ...

Gosh ... I'm so sorry for this ... I believe I didn't make any errors, because all (or most of it - exception for switch ) worked yesterday ...

... I just checked out old commit (with not working switch) from two days ago, to keep working on theme ...

**Comment by aristath** [comment]
@Anydog could you please elaborate a bit more on the issues you're having?

> default values not loaded in preview

Is that on some specific fields?

> font changes ( I used select2 and Kirki_Fonts::get_font_choices with array( 'element' => 'body', 'property' => 'font-family',) in "output" ) - although, those are saved and visible on frontend

You say the options are saved & applied on the fromthend, so... what doesn't work?

> number slider (also, saved successfully on frontend)

What is it that does not work in the slider field?

> image upload not being previewed AND saved ...

are you using `js_vars` or `output` on image fields?
Can you please post the code you're using for a non-working image field so that I may try to figure out what doesn't work?

> and still ... switch is not saving at all ...

fixed in https://github.com/aristath/kirki/commit/dfdbacd0af10a49681b30b6ec70c4344cc82a17c

**Comment by Anydog** [comment]
Sorry, I thought I was precise enough ...  I just wanted to be short ...
- any default value fields wasn't loaded in TC (Theme Customizer) preview
- yeah, when I was making changes in TC the reload didn't apply to preview - only the colors ( I used them for fonts, backgrounds etc. - it was applied inline)
-  I used number for logo size, the preview in TC didn't apply (after refresh), but when saved, in other tab/window with full frontend it applied. The changes was saved but not visible in TC preview.
-  for image upload, I did use "output" but didn't "js_vars" ...  but it worked before without "js_vars"...
  Now I tested with "js_vars", and preview of images still doesn't work. Here's my code:

``` php
add_filter( 'kirki/fields', 'as_customizer_logo' );
function as_customizer_logo( $fields ) {

    $fields[] = array(
        'type'        => 'image',
        'settings'    => 'site_logo',
        'label'       => __( 'Site logo', 'larix' ),
        'description' => __( 'Upload or choose from media library the logo for site.', 'larix' ),
        'help'        => __( 'If you\'re going to use logo upload image here', 'larix' ),
        'section'     => 'logo_section',
        'default'     => get_template_directory_uri() . '/img/logo.svg',
        'priority'    => 10,
        'output'      => array(
            array(
                'element'   => 'header #site-title span.logo',
                'property'  => 'background-image',
            ),
        ),
        'js_vars'     => array(
            array(
                'element'  => 'header #site-title span.logo',
                'function' => 'css',
                'property' => 'background-image',
            )
        )
    );
}
```

**Comment by Anydog** [comment]
Sorry, this was my mistake - the "element" wasn't specified enough, and it was overwritten by more specified theme style. Sorry again. :flushed:

But, the switch element still doesn't work. I don't need it in preview (most of switches I created), but it's not being saved :confused:

**Comment by Anydog** [comment]
The switch element I'm using, example - I didn't add "output" and "js_vars" because it wasn't needed for live preview. Here's my switch example:

``` php
add_action( 'init', 'as_kirki_settings_general', 1 );
function as_kirki_settings_general() {

    Kirki::add_field( 'as_customizer', array(
        'type'        => 'switch',
        'settings'    => 'dynamic_css_js',
        'label'       => __( 'DYNAMIC JS and CSS files', 'larix' ),
        'description' => __( 'use dynamic javascript and css file creation instead of writing in server', 'larix' ),
        'help'        => __( 'DYNAMIC and CSS JS FILES</strong> are AJAX created and loaded styles and scripts via Wordpress admin ajax. This is alternative to default, creating javascript files upon theme customizer saving. Use in case of write/execute restrictive servers', 'larix' ),
        'section'     => 'general_settings_section',
        'default'     => '0',
        'priority'    => 10,
    ) );
}
```

**Comment by Anydog** [comment]
Oh, yeah - and from the latest pull, the default values are working ok ... Theme preview is loading defaults. So, at the moment, only switch is the issue still
But what about typography field ? Did you removed it ?

Thanks again, and sorry for the nag ...

**Comment by aristath** [comment]
Can you please try the following and let me know if you have an issue:
- Activate a dummy theme like for example the twentythirteen theme
- delete the kirki plugin, pull a fresh copy & activate it
- Make sure no other plugins are activated on your test site
- un-comment the `include_once( KIRKI_PATH . '/sample-config.php' );` line near the end of the main `kirki.php` file ( right now it's here: https://github.com/aristath/kirki/blob/master/kirki.php#L138)

This is what I use for my tests, so at least we'll be using the same data and we'll be able to figure things out easier... Are you still having an issue using those demo fields?

**Comment by Anydog** [comment]
I did all that ( switched theme to TwentyThirteen, disabled all plugins, deleted old Kirki, pulled latest, and tested with sample-config., and Kirki plugin ONLY on)
Here's the screencast video what it looks:

**http://youtu.be/j_gqlnw9DnA**

You'll notice also that, when I change the state of switch off/on, saving is still disabled. Only when I check / uncheck the checkbox, saving is enabled.
And, sorry to say, you 'll also see in the video that, after saving, switches revert to default state ... :confused:

(sorry for the tacky music in background, it's auto-generated  :smirk: )

**Comment by aristath** [comment]
Wow, that's uberweird...
I was previously conducting all my tests with the twentyfifteen theme.
Using that theme, the bug was not occuring.
However as soon as I switched to twentythirteen I could replicate it just fine.

There was an issue in the control's script, I'm pushing a fix for that now.

Thanks for taking the time to explain things man, I really appreciate it!

**Comment by Anydog** [comment]
Thanks !
( since you're here... ;) ) how to utilize "typography" field ? I added

``` php
'output'      => array(
        array(
            'element'  => 'body',
            'property' => 'font-family',
        ),
    ),
```

and it returned a bunch of errors:

```
Warning: array_key_exists(): The first argument should be either a string or an integer in ...\kirki\includes\class-kirki-fonts-font-registry.php on line 72

Notice: Array to string conversion in ...\kirki\includes\class-kirki-fonts-font-registry.php on line 84

Notice: Array to string conversion in ...\kirki\includes\class-kirki-fonts-font-registry.php on line 84

Warning: array_key_exists(): The first argument should be either a string or an integer in ...\kirki\includes\class-kirki-fonts-font-registry.php on line 72

Warning: array_key_exists(): The first argument should be either a string or an integer in ...\kirki\includes\class-kirki-fonts-font-registry.php on line 72

Notice: Array to string conversion in ...\kirki\includes\class-kirki-fonts-font-registry.php on line 84

Notice: Array to string conversion in ...\kirki\includes\class-kirki-fonts-font-registry.php on line 84

Warning: array_key_exists(): The first argument should be either a string or an integer in ...\kirki\includes\class-kirki-fonts-font-registry.php on line 72
```

**and a lot of these:**

```
Warning: array_merge_recursive(): Argument #2 is not an array in ...\kirki\includes\class-kirki-output.php on line 271
```

.... sorry ...

**Comment by aristath** [comment]
The 'output' argument doesn't work (yet) for the typography & spacing fields...
All fields save their values as strings.
these 2 new fields however save their values as arrays and I haven't modified the code responsive for the 'output' argument to handle that properly yet.

For the time being you can write your own code...
Something like this for example could be used to generate the CSS:

``` php
// We're assuming a setting with id = 'my_setting'
$value = get_theme_mod( 'my_setting', array() );

$css = 'body #content {';
foreach( $value as $property => $value ) {
    $css .= $property . ':' . $value . ';';
}
$css .= '}';
```

Or you could wait a couple of days 'till I figure out a way to automate this. ;)

**Comment by Anydog** [comment]
Thank you very much. Looking forward for "output" implementation.
One more thing (I know you'll hate me :) ) . Default values just don't load to TC preview, and (other then color controls) changes are not visible too. See my theme video here:

**http://youtu.be/4zEyfrWQC9s**

This is just a short example:
- in first tab there's TC with not loaded defaults ( font should be Roboto and Roboto Condensed but they aren't)
- in second tab there's a frontend where all saved changes from TC are, in fact applied

... sorry, again ... :flushed:

**Comment by aristath** [comment]
So... let me see if I understand correctly.
The fields work fine, they save their options just fine and the only issue is the 'output' argument.
Correct?
If this is the case, then I've already started working on rebuilding that from scratch.

**Comment by aristath** [comment]
@Anydog can you please pull the latest commit and let me know if it works for you now?

If not then do you have that theme somewhere on github so that I may download it and test this for myself? It's gonna save us some time. :)

**Comment by Anydog** [comment]
Hi,
Wow, I don't really don't believe that it would be needed work from scratch ... 
Especially because it works now !! :sparkles: :star: :sparkles:

It worked ok some 4-5 days ago, it's just, from latest pulls it broke ... 
But, from latest pull it seems everything to be ok.

Anyhow, I sent my theme to DropBox and email invite to aristath@gmail.com , because I cannot add it to public git repository, since it's going to be premium theme.

**Comment by Anydog** [comment]
Hi,
just to tell you I really appreciate all the work you do. Did you receive my email with theme ? What do you think of it ... ?
