### ISSUE TITLE
Fatal error: Class 'Avada_Sanitize_Values' not found

### ISSUE THREAD

**Issue by dameer** [themeum/kirki#736]
After an update to version 2.2.0 Customizer reports some strange error:

_Fatal error: Class 'Avada_Sanitize_Values' not found in ...wp-content/plugins/kirki/includes/output/property/class-kirki-output-property-background-position.php on line 29_

Version used: 2.2.0

Using theme_mods or options? **theme_mods**

Code to reproduce the issue (config + field(s)) : no changes in code since version 2.1.0.1

**Comment by aristath** [comment]
This makes no sense...
The `Avada_Sanitize_Values` exists in the `includes/class-kirki-sanitize-values.php` file and is loaded from the `autoloader.php` file, which in its turn is the first thing that gets loaded when the main `kirki.php` file is loaded.

The only thing that I can think of that would cause this is if Kirki is loaded inside an action that runs too late...
How exactly are you including Kirki?

**Comment by dameer** [comment]
I don't know what's going on mate, all I did is an update from 2.1.0.1 to 2.2.0 via WP plugins screen. I'm on localhost (PHP 5.5.24, mySQL 5.6.24) with the latest WP 4.4.2.

![avada_error](https://cloud.githubusercontent.com/assets/1826261/13852492/8fc41074-ec62-11e5-8d4b-2ca9fee62b65.png)

Forgot to say that I'm not embedding Kirki, I'm using it as a plugin.

**Comment by aristath** [comment]
Can you please send me a copy of your theme so that I may test this on my localhost?

**Comment by aristath** [comment]
Actually, I just pushed a potential fix for this, can you please try downloading the develop branch from this repository and test if this fixes it for you?
I can't replicate it, so I'm going blind here :P

**Comment by dameer** [comment]
Do I need to merge remote-tracking branch 'aristath/master' into my own? Sorry, I'm not a Github geek.

**Comment by aristath** [comment]
Just download the zip file from here: https://github.com/aristath/kirki/archive/develop.zip
remove the previous copy of kirki from wp-content, extract the zip file you just downloaded in wp-content and make sure you rename the extracted folder to "kirki".

**Comment by dameer** [comment]
No, unfortunately it didn't help. The same error persists, pointing to the same file and line number.

**Comment by aristath** [comment]
can you try now?

**Comment by dameer** [comment]
Now an error points to line 32. Is the problem possibly theme related? I mean, it's OK if I switch to one of WP's default themes, however, none of it has nothing to do with Kirki...

**Comment by aristath** [comment]
Can you please send me a copy of your theme via email? I'll install it and try to replicate this locally...

**Comment by dameer** [comment]
I'm not sure I am allowed to share the theme, it's commercial one and I'm participant. Would you like me to push it to the remote server and then create admin credentials for you? Is that something that might help?

**Comment by aristath** [comment]
> I'm not sure I am allowed to share the theme, it's commercial one and I'm participant.

I'm sure the developer of the theme would have no objection to me using a copy of their theme for debugging purposes... After all, if they use Kirki for their theme they'll want it to work without any issues. It's a pretty common practice.

> Would you like me to push it to the remote server and then create admin credentials for you? Is that something that might help?

If I have not only admin credentials for the site but also FTP credentials for that server so that I may debug the issue then yes, that could also work.

Sending the theme via email is just faster and more convenient than debugging & editing files via FTP.

**Comment by aristath** [comment]
You could also send me via email the email address of the developer so that I may contact them directly?

**Comment by dameer** [comment]
Well, I guess no one will know and you are right. Theme copy sent to your e-mail address. Thanks for your time!!!

**Comment by aristath** [comment]
ok, found it.

I had a typo and couldn't figure it out... Sometimes the issue is right in front of and you still can't see it. :+1: 

Thanks buddy, that really helped me figure things out!

**Comment by dameer** [comment]
Great! I'm glad to be helpful. I suppose the issue will be fixed in Kirki version 2.2.1, right?

**Comment by aristath** [comment]
right. pushing it in a few minutes :)
