### ISSUE TITLE
Color picker generates double hash output for color causing browser to ignore

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#747]
### Issue description:

Color picker for any element without alpha stores value with hash in front of hex color.  Output CSS by Kirki adds another hash in front doubling the hashes.  Works in customizer using js_vars but not in output.  Makes no difference if transport is refresh or postMessage.
### Version used:

Wordpress Plugin Repository version 2.2.3
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

``` php
  /**
   * Background Color
   */
  designer_Kirki::add_field( 'designer', array(
    'type'        => 'color',
    'label'       => __( 'Background Color', 'designer' ),
    'description' => __( 'Choose a background accent color.', 'designer' ),
    'settings'    => 'background_color',
    'priority'    => $priority++,
    'section'     => $section,
    'default'     => '#f9f9f9',
    'transport'   => 'postMessage',
    'output'   => array(
        array(
            'element'  => 'body',
            'property' => 'background-color',
            'prefix'   => ''
        )
    ),      
    'js_vars'     => array(
      array(
        'element'  => 'body',
        'function' => 'css',
        'property' => 'background-color'
      )
    )
  ) );
```

**Comment by aristath** [comment]
@webeau can you please try pulling the latest develop branch and let me know if that fixes your issue?
It seems to be working fine for me now.

**Comment by ghost** [comment]
I did a pull and it work without error for this issue.  Fixed in the development branch.

**Comment by aristath** [comment]
Awesome, thanks for checking!

**Comment by ghost** [comment]
I am investigating this a bit further.  I'm afraid I was a bit lazy and checked this against a different theme using the development pull.  Both themes are similar in construction but the one I tested it on the second time was completely homegrown and used an embedded Kirki already rather than the plugin (so easy test against).  I have since modified the first theme (the one that initiated this issue) to embed the latest pull and disabled the plugin - making them even more similar.  Still getting double hashes using the first theme.  That theme is based upon the kirki helpers and your fork of _s.  If I find an issue I will open it in the appropriate place but it appears the problem was not related to the plugin release after all.

**Comment by aristath** [comment]
Is this theme using exclusively the output argument for color controls? Is there perhaps any other custom code involved that would effect this?
Could you send me a copy of the theme so that I may further investigate this?

**Comment by aristath** [comment]
@webeau Any update on this one?
I'm still unable to replicate your issue no matter what I try, so the only way to resolve it is if I get a copy of the theme that has this issue

**Comment by aristath** [comment]
Closed due to inactivity.
If you're still having this issue using the latest develop branch then please feel free to reopen this ticket and post an update on your current status
